const MATCH_STATUS_GENERAL = {
  CANCELLED: 3,
  DELAYED: 2,
  FINAL: 1,
  INTERRUPTED: 5,
  // 0-19
  NOT_STARTED: 0,
  OTHER: 4,
};

const FOOTBALL_MATCH_STATUS = {
  ...MATCH_STATUS_GENERAL,
  AWAITING_EXTRA_TIME: 23,
  AWAITING_PENALTIES: 28,
  FINAL_EXTRA_TIME: 27,
  FINAL_PENALTIES: 30,
  FIRST_EXTRA_TIME: 24,
  // 20-39
  FIRST_HALF: 20,
  HALFTIME: 21,
  HALFTIME_EXTRA_TIME: 25,
  PENALTIES: 29,
  SECOND_EXTRA_TIME: 26,
  SECOND_HALF: 22,
};

const AMERICAN_FOOTBALL_MATCH_STATUS = {
  ...MATCH_STATUS_GENERAL,
  AWAITING_OVERTIME: 47,
  END_FIRST_QUARTER: 41,
  END_THIRD_QUARTER: 45,
  FINAL_OVERTIME: 49,
  // 40-59
  FIRST_QUARTER: 40,
  FOURTH_QUARTER: 46,
  HALFTIME: 43,
  OVERTIME: 48,
  SECOND_QUARTER: 42,
  THIRD_QUARTER: 44,
};

export const MATCH_STATUS_LABELS = {
  [AMERICAN_FOOTBALL_MATCH_STATUS.AWAITING_OVERTIME]: 'OT',
  [AMERICAN_FOOTBALL_MATCH_STATUS.END_FIRST_QUARTER]: 'Fim 1Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.END_THIRD_QUARTER]: 'Fim 3Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.FINAL_OVERTIME]: 'Fim OT',
  [AMERICAN_FOOTBALL_MATCH_STATUS.FIRST_QUARTER]: '1Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.FOURTH_QUARTER]: '4Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.HALFTIME]: 'HT',
  [AMERICAN_FOOTBALL_MATCH_STATUS.OVERTIME]: 'OT',
  [AMERICAN_FOOTBALL_MATCH_STATUS.SECOND_QUARTER]: '2Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.THIRD_QUARTER]: '3Q',
  [FOOTBALL_MATCH_STATUS.AWAITING_EXTRA_TIME]: 'TE',
  [FOOTBALL_MATCH_STATUS.AWAITING_PENALTIES]: 'Pen',
  [FOOTBALL_MATCH_STATUS.FINAL_EXTRA_TIME]: 'Fim TE',
  [FOOTBALL_MATCH_STATUS.FINAL_PENALTIES]: 'Fim Pen',
  [FOOTBALL_MATCH_STATUS.FIRST_EXTRA_TIME]: '1TE',
  [FOOTBALL_MATCH_STATUS.FIRST_HALF]: '1T',
  [FOOTBALL_MATCH_STATUS.HALFTIME]: 'Int',
  [FOOTBALL_MATCH_STATUS.HALFTIME_EXTRA_TIME]: 'Int TE',
  [FOOTBALL_MATCH_STATUS.PENALTIES]: 'Pen',
  [FOOTBALL_MATCH_STATUS.SECOND_EXTRA_TIME]: '2TE',
  [FOOTBALL_MATCH_STATUS.SECOND_HALF]: '2T',
  [MATCH_STATUS_GENERAL.CANCELLED]: 'Cancel',
  [MATCH_STATUS_GENERAL.DELAYED]: 'Adiado',
  [MATCH_STATUS_GENERAL.FINAL]: 'Fim',
  [MATCH_STATUS_GENERAL.INTERRUPTED]: 'Interr',
  [MATCH_STATUS_GENERAL.NOT_STARTED]: '',
  [MATCH_STATUS_GENERAL.OTHER]: 'Outro',
};

// const STOPPED_GAME = [
//   MATCH_STATUS_GENERAL.NOT_STARTED,
//   MATCH_STATUS_GENERAL.FINAL,
//   MATCH_STATUS_GENERAL.DELAYED,
//   MATCH_STATUS_GENERAL.CANCELLED,
//   MATCH_STATUS_GENERAL.OTHER,
//   MATCH_STATUS_GENERAL.INTERRUPTED,
//   FOOTBALL_MATCH_STATUS.HALFTIME,
//   FOOTBALL_MATCH_STATUS.AWAITING_EXTRA_TIME,
//   FOOTBALL_MATCH_STATUS.HALFTIME_EXTRA_TIME,
//   FOOTBALL_MATCH_STATUS.FINAL_EXTRA_TIME,
//   FOOTBALL_MATCH_STATUS.AWAITING_PENALTIES,
//   FOOTBALL_MATCH_STATUS.FINAL_PENALTIES,
//   AMERICAN_FOOTBALL_MATCH_STATUS.END_FIRST_QUARTER,
//   AMERICAN_FOOTBALL_MATCH_STATUS.HALFTIME,
//   AMERICAN_FOOTBALL_MATCH_STATUS.END_THIRD_QUARTER,
//   AMERICAN_FOOTBALL_MATCH_STATUS.AWAITING_OVERTIME,
//   AMERICAN_FOOTBALL_MATCH_STATUS.FINAL_OVERTIME,
// ];

export const MATCH_STATUS = {
  CANCELLED: MATCH_STATUS_GENERAL.CANCELLED,
  DELAYED: AMERICAN_FOOTBALL_MATCH_STATUS.DELAYED,
  END_FIRST: AMERICAN_FOOTBALL_MATCH_STATUS.END_FIRST_QUARTER,
  END_THIRD: AMERICAN_FOOTBALL_MATCH_STATUS.END_THIRD_QUARTER,
  FINAL: MATCH_STATUS_GENERAL.FINAL,
  FINAL_OVERTIME: AMERICAN_FOOTBALL_MATCH_STATUS.FINAL_OVERTIME,
  FIRST: AMERICAN_FOOTBALL_MATCH_STATUS.FIRST_QUARTER,
  FOURTH: AMERICAN_FOOTBALL_MATCH_STATUS.FOURTH_QUARTER,
  HALFTIME: AMERICAN_FOOTBALL_MATCH_STATUS.HALFTIME,
  NOT_STARTED: MATCH_STATUS_GENERAL.NOT_STARTED,
  OTHER: MATCH_STATUS_GENERAL.OTHER,
  OVERTIME: AMERICAN_FOOTBALL_MATCH_STATUS.OVERTIME,
  SECOND: AMERICAN_FOOTBALL_MATCH_STATUS.SECOND_QUARTER,
  THIRD: AMERICAN_FOOTBALL_MATCH_STATUS.THIRD_QUARTER,
};

export const FINISHED_GAME = [MATCH_STATUS.FINAL, MATCH_STATUS.FINAL_OVERTIME, MATCH_STATUS.CANCELLED];
export const STOPPED_GAME = [
  MATCH_STATUS.FINAL,
  MATCH_STATUS.FINAL_OVERTIME,
  MATCH_STATUS.CANCELLED,
  MATCH_STATUS.END_FIRST,
  MATCH_STATUS.END_THIRD,
  MATCH_STATUS.HALFTIME,
  MATCH_STATUS.DELAYED,
  MATCH_STATUS.NOT_STARTED,
  MATCH_STATUS.NOT_STARTED,
];

export type TMatchStatus = (typeof MATCH_STATUS)[keyof typeof MATCH_STATUS];
