name: Trello Card & GitHub PR Integration
on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, converted_to_draft]
  issue_comment:
    types: [created, edited]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trello:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: rematocorp/trello-integration-action@v10.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trello-api-key: ${{ secrets.TRELLO_API_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_AUTH_TOKEN }}
          trello-list-id-pr-open: 69f864d58356f5f5e0d15442
          trello-list-id-pr-closed: 69f8ce4d7caf6cebcb9fb5fe

# https://github.com/rematocorp/trello-integration-action
